description: |
  Apply a Prodvana config file.

usage:
  version: 2.1

  orbs:
    prodvana: prodvana/prodvana@x.y.z

  jobs:
    deploy:
      docker:
        - image: cimg/base:stable
      steps:
        - checkout
        - prodvana/install-pvnctl
        - prodvana/config-apply:
            path: testdata/configs/runtimes/...
        - prodvana/config-apply:
            app: my-app
            service: bar-service
            docker-image: myrepo/bar:v2.0.1
            wait-channels: dogfood,staging

  workflows:
    my-workflow:
      jobs:
        - deploy
